### ISSUE TITLE
mstickereditor is outdated

### ISSUE THREAD

**Issue by LuckyTurtleDev** [linyinfeng/nur-packages#373]
https://github.com/LuckyTurtleDev/mstickereditor/releases/tag/v0.3.2

**Comment by linyinfeng** [comment]
Thank you! The auto update PR was blocked due to missing dependency `libavutil`. Fixed in <https://github.com/linyinfeng/nur-packages/pull/374/commits/5f678fd41bd5f9084d8cdd9c4c4d617c6dd32c68>. `v0.3.2` is in master now.
