### ISSUE TITLE
Wemeet (X) cannot share screen in wayland

### ISSUE THREAD

**Issue by Freed-Wu** [linyinfeng/nur-packages#485]
The package script is modified from [AUR](https://aur.archlinux.org/packages/wemeet-bin) which add a Wemeet (X) to support share screen on Wayland.

However, I try wemeet (X) cannot share screen in wayland.

Is it a bug of upstream [AUR](https://aur.archlinux.org/packages/wemeet-bin)'s Wemeet (X)?

**Comment by linyinfeng** [comment]
Wemeet itself does not support screen capturing on Wayland.

The AUR script does not fix screen capturing on Wayland. It only forces Wemeet to run on XWayland.
```bash
if [ "$(basename "$0")" = 'wemeet-x11' ]; then
    # force x11
    export XDG_SESSION_TYPE=x11
    export QT_QPA_PLATFORM=xcb
    unset WAYLAND_DISPLAY
fi
```

You may follow the pinned comment of the [wemeet-bin](https://aur.archlinux.org/packages/wemeet-bin) for a workaround, sharing the screen with a virtual video device.

**Comment by Freed-Wu** [comment]
> forces Wemeet to run on XWayland.

Does force Wemeet to run on XWayland still cannot use screen capturing?

**Comment by linyinfeng** [comment]
> > forces Wemeet to run on XWayland.
> 
> Does force Wemeet to run on XWayland still cannot use screen capturing?

Yes, still cannot use screen capturing.
